apiVersion: v1 
kind: Service 
metadata: 
  name: order-svc-clusterip 
  labels: 
    svc: order-svc-def  
spec: 
  selector: 
    app: my-order-service
  ports: 
    - port: 3004 
      targetPort: 3004  
      